export const countries = [
    "Russia",
    "Mongolia",
    "Kazakhstan",
    "Kyrgyzstan",
    "Tajikistan",
    "Turkmenistan",
    "Uzbekistan",

    "Albania",
    "Andorra",
    "Austria",
    "Belarus",
    "Belgium",

    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "Latvia",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Moldova",
    "Monaco",
    "Montenegro",
    "Netherlands",

    "Norway",
    "Poland",
    "Portugal",
    "Romania",
    "San Marino",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "Ukraine",
    "United Kingdom",
    "Vatican City",

    "Argentina",
    "Bahamas",
    "Barbados",
    "Belize",
    "Bolivia",
    "Brazil",
    "Canada",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "El Salvador",
    "Grenada",
    "Guatemala",
    "Guyana",
    "Haiti",
    "Honduras",
    "Jamaica",
    "Mexico",
    "Nicaragua",
    "Panama",
    "Paraguay",
    "Peru",
    "Saint Lucia",
    "Suriname",

    "United States",
    "Uruguay",
    "Venezuela",
  ].sort();

  export const dummyData = [
  {
    id: 1,
    tracking: "CG2254785544562036_CARGO",
    receiver: "John Doe",
    status: "In Transit",
  },
  {
    id: 2,
    tracking: "CG8894785552011342_CARGO",
    receiver: "Sarah Jenkins",
    status: "Delivered",
  },
  {
    id: 3,
    tracking: "CG1102955456638475_CARGO",
    receiver: "Michael Chen",
    status: "Held at Customs",
  },
];

 export const userData = [
    { id: 1, name: "Jolene", initial: "JM", text: "I have had the most exceptional customer service ever. The website is easy to use, great rates! And I love the SwiftSphere theme chats lol. Very happy I chose y'all for the service" },
    { id: 2, name: "Gina", initial: "GA", text: "The most amazing self shipping company. The Best communication, prices, and its fun. 😊 Thank you so much. LifeLong customer right here. Get on board mates" },
    { id: 3, name: "Lee", initial: "LC", text: "I have been telling all my small business friends to 'Become a SwiftSphere'! Better rates...easy label printing, and address storage of previous customers" },
    { id: 4, name: "Sarah", initial: "SK", text: "SwiftSphere made my logistics nightmare a dream. Fast, reliable, and consistent service every time." },
    { id: 5, name: "Mike", initial: "MT", text: "Best in the business. The eagle tracking feature is actually helpful, not just a gimmick." },
    { id: 6, name: "Anna", initial: "AR", text: "Seamless integration with my furnitures store. I don't use anyone else for my shipping needs now." },
    { id: 7, name: "David", initial: "DW", text: "Customer support stayed on the line with me for an hour to fix a routing issue. Truly exceptional." },
    { id: 8, name: "Chloe", initial: "CP", text: "Loved the experience and the transparency in pricing. No hidden fees, just pure speed and efficiency." },
    { id: 9, name: "Ben", initial: "BJ", text: "My e-commerce brand grew up considerably since switching to SwiftSphere transit times." },
    { id: 10, name: "Emma", initial: "EL", text: "Reliable, professional, and the automated info storage saves me hours every week!" },
  ];

  export const languages = [
    { code: "US", name: "English", lang: "en" },
    { code: "FR", name: "Français", lang: "fr" },
    { code: "ES", name: "Español", lang: "es" },
    { code: "CN", name: "中文", lang: "zh" },
    { code: "DE", name: "Deutsch", lang: "de" },
    { code: "IT", name: "Italiano", lang: "it" },
    { code: "PT", name: "Português", lang: "pt" },
    { code: "RU", name: "Русский", lang: "ru" },
    { code: "PL", name: "Polski", lang: "pl" }, 
    { code: "NO", name: "Norsk", lang: "no" },  
    { code: "SE", name: "Svenska", lang: "sv" }, 
    { code: "NL", name: "Nederlands", lang: "nl" }, 
    { code: "FI", name: "Suomi", lang: "fi" },
    { code: "RO", name: "Română", lang: "ro" },
    { code: "JP", name: "日本語", lang: "ja" },
    { code: "SA", name: "العربية", lang: "ar" },
    { code: "NG", name: "Hausa", lang: "ha" },
    { code: "KR", name: "한국어", lang: "ko" },
    { code: "TR", name: "Türkçe", lang: "tr" },
    { code: "VN", name: "Tiếng Việt", lang: "vi" },
    { code: "IN", name: "हिन्दी", lang: "hi" },
    { code: "ID", name: "Bahasa Indonesia", lang: "id" },
    { code: "TH", name: "ไทย", lang: "th" },
    { code: "PK", name: "اردو", lang: "ur" },
    { code: "IR", name: "فارسی", lang: "fa" },
    {code: "UA", name: "Ukraine", lang: "ua"}
  ];
